### ISSUE TITLE
Marker click listener doesn't work

### ISSUE THREAD

**Issue by sorinirimies** [googlemaps/android-maps-ktx#102] opened 2020-10-02 12:17 UTC
####Issue:
Google Maps Marker click listener callback doesn't return 

#### Environment details
Android version: 10
Android SDK: 29
Kernel Version: 4.14.117-perf+
Battery: 57%
Locale: en_US
Uptime: 24:19:36 h
Model: GM1900
Internal Model: 2007240000
Architecture: aarch64
Number of Cores: 8
Free disk space: 144.20 GB
Free RAM: 148.61 MB
Total memory: 7.30 GB
Available memory: 1.90 GB
Threshold memory: 216.00 MB
Low memory: false

#### Steps to reproduce
  1. Start map and load markers
  2. Click on any map marker visible

**Comment by arriolac** [comment] 2020-10-02 17:22
Can you provide a code snippet to help debug this?

**Comment by sorinirimies** [comment] 2020-10-04 18:37
Thx for your answer. Yes sure. 
So we have a class called `GoogleMapInstance` where we fetch `GoogleMap` instance and perform also other common actions.
This class, represented through an interface is then used within a so called `MapWrapper` which brings together the map functionality and the functionality of several adapters.


Long story short, here is the code for the `GoogleMapInstance` where we set the clickListener:
```
internal class GoogleMapsInstance(
    private val context: Context,
    private val googleMapsFragment: SupportMapFragment
) : MapInstance {
    private lateinit var map: GoogleMap

    private lateinit var clusterManager: ClusterManager<MapClusterItem>

    override val currentZoomLevel: Float?
        get() {
            return map.cameraPosition?.zoom
        }

    private val poiList = mutableListOf<Poi>()
    private val areaList = mutableListOf<Area>()
    private val polylineList = mutableListOf<PorschePolyline>()
    private var poiClickListener: (Poi) -> Boolean = { false }
    private var areaClickListener: (Area) -> Boolean = { false }
    private var clusterListener: (MapLocation) -> Boolean = { false }

    override suspend fun init(style: MapStyle, interactive: Boolean, mapPadding: MapPadding?) {
        map = googleMapsFragment.awaitMap()

        when (style) {
            is MapStyle.Plain -> map.plainStyle(context)
            is MapStyle.Custom -> map.customStyle(context, style.styleResource)
        }

        if (!interactive) {
            map.uiSettings.setAllGesturesEnabled(false)
        }

        mapPadding?.let {
            map.setPadding(
                it.left,
                it.top,
                it.right,
                it.bottom
            )
        }
        clusterManager = ClusterManager(context, map)
        val clusterRenderer = ClusterRenderer(context, map, clusterManager)
        clusterManager.renderer = clusterRenderer
        clusterManager.algorithm = GridBasedAlgorithm()

        map.setOnMarkerClickListener { marker ->
            when {
                clusterManager.clusterMarkerCollection.markers.contains(marker) -> clusterListener(
                    MapLocation(marker.position.latitude, marker.position.longitude)
                )
                else -> poiClickListener(GooglePoi(context, marker))
            }
        }
        mapType = NORMAL
    }
. . .
```
The `MapWrapper`which passes the boolean lambda :
 ```

class MapWrapper(private val map: MapInstance, interactive: Boolean) {

    private val adapters: MutableList<AdapterWrapper<*>> = mutableListOf()
    private var onClickBlock: () -> Unit = {}
    private var onIdleBlock: (visibleRegion: Rect) -> Unit = {}
    private var onClusterBlock: (MapLocation) -> Unit = {}

    init {
        if (interactive) {
            map.setOnPoiClickListener {
                for (adapter in adapters) {
                    return@setOnPoiClickListener adapter.adapter.handleMarkerClick(it, this)
                }
                false
            }
            map.setOnAreaClickListener {
                for (adapter in adapters) {
                    return@setOnAreaClickListener adapter.adapter.handlePolygonClick(it, this)
                }
                false
            }
            map.setOnCameraIdleListener {
                onIdleBlock(map.getVisibleRegion())
            }
            map.setOnMapClickListener { onClickBlock() }
            map.setOnClusterClickListener {
                onClusterBlock(it)
                true
            }
        }
    }
. . . 
```
And lastly, the `MapAdapter` which is the consumers or the clickListener and is reponsable to return the boolean value:
```
    override fun handleMarkerClick(poi: Poi, mapWrapper: MapWrapper): Boolean {
        val mapPoi = poi.tag as? MapAdapterPoiItem ?: return false
        trackOnScreenEvent("TapExploreVehicleIcon", "Explore")
        mapItemClickListener(mapPoi)
        return true
    }
. . .
```

**Comment by sorinirimies** [comment] 2020-10-04 18:46
The problem is however, that it doesn't reach the adapter. Based on the debugging I performed, the original `map.setOnClickListener{. . .}` doesn't get called when clicking on the marker.

**Comment by arriolac** [comment] 2020-10-05 16:55
Ah, looks like the issue is related to your use of clustering in the Utility Library. There have been some breaking changes and a [migration guide](https://github.com/googlemaps/android-maps-utils#adding-click-events) has been written as a result. `ClusterManager` internally calls `GoogleMap#setOnMapClickListener` so it is necessary to call the set listener functions on the `ClusterManager` instead.

i.e.

```
clusterManager.setOnClusterItemClickListener { item ->
    // Listen for clicks on a cluster item here
    false
}
clusterManager.setOnClusterClickListener { cluster ->
    // Listen for clicks on a cluster here
    false
}
```

**Comment by sorinirimies** [comment] 2020-10-06 13:35
Ahhh, ok. Thx. Is there a way maybe like a Ktlint to notify the users of this. Or a warning annotation or something.
Because, it is a little bit unintuitive at first usage.
Thx for the info I will change it accordingly.

**Comment by sorinirimies** [comment] 2020-10-06 13:43
Because in our case for example, we use a cluster manager for one of the adapters but for the other adapter we don't. However, we provide all as POIs on the map.

**Comment by sorinirimies** [comment] 2020-10-06 14:08
Ok, so I tried it out but now the problem I have is that I need Markers in some cases, as in some cases we don't cluster some markers together.
Which leads me to the following logic:
If I have a map instance where I partly have cluster-able items like gas stations and what not, and on the other hand I have some items that I don't want to cluster, like a car, or some favourite place, then it will be hard to do that given this setup or?

**Comment by arriolac** [comment] 2020-10-06 20:46
The example in https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/MultiLayerDemoActivity.java#L136...L150 demonstrates exactly what you need. You would have to create a `MarkerManager.Collection` from the `MarkerManager` class that you provide to `ClusterManager`. 

I agree that the API is not ideal and we should lean on tools like a lint check to offer these suggestions proactively.

**Comment by arriolac** [comment] 2020-10-08 17:21
@sorinirimies did that information address your issue? Let me know otherwise so we can close this. Thanks!

**Comment by sorinirimies** [comment] 2020-10-08 17:23
It did thanks. You can close it.

**Closed** 2020-10-08 17:26 UTC
Labels: triage me, type: bug
